import { createContext, useContext, useState, type ReactNode } from "react";

type Lang = "en" | "sv";

const en = {
    // ── Header / brand ─────────────────────────────────────────────
    brand_subtitle:         "Competition Hub",

    // ── Public nav ─────────────────────────────────────────────────
    nav_registration:       "Register players",
    nav_login:              "Login",
    nav_login_admin:        "Login as Admin",
    nav_login_club:         "Login as Club",

    // ── Home hero ──────────────────────────────────────────────────
    hero_eyebrow:           "HSC Competition System",
    hero_title:             "The competition hub for horseshoe throwing.",
    hero_copy:              "Log in as Admin to manage competitions and results, or log in as Club to register your players.",
    hero_btn_login_admin:   "Login as Admin",
    hero_btn_login_club:    "Login as Club",

    // ── Home calendar panel ────────────────────────────────────────
    panel_kicker:           "Season 2026",
    panel_heading:          "Upcoming competitions",
    panel_empty:            "No upcoming competitions found.",
    panel_view_all:         "View all competitions",
    status_open:            "Open",
    status_closed:          "Closed",

    // ── Competitions public page ───────────────────────────────────
    back_home:              "Home",
    comps_eyebrow:          "Season 2026",
    comps_heading:          "All competitions",
    comps_copy:             "Full season calendar synced from svhkf.se.",
    comps_upcoming:         "Upcoming",
    comps_past:             "Past",
    comps_empty:            "No competitions found. Check back later.",
    ranking:                "Ranking",

    // ── Registration page ──────────────────────────────────────────
    reg_back_home:          "Home",
    reg_back_public:        "Public home",
    reg_eyebrow:            "Register players",
    reg_heading:            "Register a player for the next HSC competition.",
    reg_copy:               "Submit player details so organizers can confirm categories, clubs, and score sheets before the event starts.",
    reg_point_1:            "Confirmation handled by the organizer",
    reg_point_2:            "Supports singles and team entries",
    reg_point_3:            "Contact details kept with the event roster",
    reg_kicker:             "Player registration",
    reg_form_heading:       "Player details",
    reg_received:           "Received",
    reg_first_name:         "First name",
    reg_last_name:          "Last name",
    reg_email:              "Email",
    reg_optional:           "(optional)",
    reg_club:               "Club",
    reg_search:             "Type to search...",
    reg_class:              "Class",
    reg_select_class:       "Select class",
    reg_class_1:            "Class 1",
    reg_class_2:            "Class 2",
    reg_class_3:            "Class 3",
    reg_class_4:            "Class 4",
    reg_title:              "Title",
    reg_select_title:       "Select title",
    reg_mr:                 "Mr.",
    reg_mrs:                "Mrs.",
    reg_junior:             "Junior",
    reg_minior:             "Minior",
    reg_notes:              "Notes",
    reg_notes_ph:           "Partner, accessibility needs, or scheduling notes",
    reg_submit:             "Submit registration",
    reg_saved:              "Registration saved in this browser. You can connect it to Supabase when the event API is ready.",

    // ── Admin sidebar ──────────────────────────────────────────────
    sidebar_subtitle:       "Competition System",
    menu_dashboard:         "Dashboard",
    menu_players:           "Players",
    menu_competitions:      "Competitions",
    menu_registration:      "Register players",
    menu_contest:           "Contest",
    menu_results:           "Results",
    menu_reports:           "Reports",
    menu_settings:          "Settings",

    // ── Topbar ─────────────────────────────────────────────────────
    topbar_title:           "Competition Manager",
    topbar_role:            "Tournament Director",
    topbar_notifications:   "Notifications",

    // ── Dashboard ──────────────────────────────────────────────────
    dash_eyebrow:           "Logged in",
    dash_heading:           "What do you want to do?",
    dash_card_reg_title:    "Register a player",
    dash_card_reg_text:     "Add a new player entry with club, category, and competition details.",
    dash_card_teams_title:  "Teams and players",
    dash_card_teams_text:   "See the full roster and review all clubs, teams, classes, and categories.",
    dash_card_start_title:  "Start a contest",
    dash_card_start_text:   "Open scoring for the active competition and begin entering results.",
    dash_current_comp:      "Current competition",

    // ── Players page ───────────────────────────────────────────────
    players_eyebrow:        "Roster",
    players_clubs_heading:  "Clubs",
    players_club_desc:      "Choose a club to see its members.",
    players_team_desc:      "Club members sorted by class and name.",
    players_all_clubs:      "All clubs",
    players_col_class:      "Class",
    players_col_name:       "Name",
    players_col_category:   "Category",
    players_col_7m:         "7-meters",
    players_col_actions:    "Actions",
    players_edit_btn:       "Edit",
    players_no_team:        "No team",
    players_class_prefix:   "Class",
    players_player_s:       "player",
    players_player_p:       "players",
    players_member_s:       "member",
    players_member_p:       "members",
    players_classes_sfx:    "classes",
    players_label_name:     "Name",
    players_label_club:     "Club",
    players_label_class:    "Class",
    players_label_category: "Category",
    players_save:           "Save",
    players_cancel:         "Cancel",

    // ── Results page ───────────────────────────────────────────────
    results_empty_heading:  "No active contest",
    results_empty_desc:     "Start a contest in Contest center to see live standings here.",
    results_eyebrow:        "Live results",
    results_updates_auto:   "updates automatically",
    results_print:          "Print",
    results_class_prefix:   "Class",
    results_col_player:     "Player",
    results_col_club:       "Club",
    results_col_total:      "Total",
    results_col_7m:         "7m",
    results_col_points:     "Points",
    results_col_num:        "#",
    results_player_s:       "player",
    results_player_p:       "players",
    results_team_heading:   "Team",
    results_team_s:         "team",
    results_team_p:         "teams",
    results_col_teams_name: "Team",
    results_col_players:    "Players",

    // ── Contest / Scoring page ─────────────────────────────────────
    sc_eyebrow_menu:        "Contest",
    sc_heading_menu:        "Contest center",
    sc_desc_menu:           "Start a new contest or open a saved contest.",
    sc_start_title:         "Start contest",
    sc_start_desc:          "Choose which contest you want to start.",
    sc_old_title:           "Old contest",
    sc_old_desc:            "Open a contest with scores saved in this browser.",
    sc_back:                "Back",
    sc_heading_choose:      "Choose contest",
    sc_desc_choose:         "Select the contest you want to start.",
    sc_heading_saved:       "Saved contests",
    sc_desc_saved:          "Select a saved contest to continue scoring.",
    sc_no_old_heading:      "No old contests",
    sc_no_old_pill:         "Empty",
    sc_no_old_desc:         "Saved contests will appear here after you start a contest and save scores.",
    sc_type_desc:           "Choose one or more contest types. Click a selected type again to cancel it.",
    sc_clear:               "Clear",
    sc_continue:            "Continue",
    sc_lanes_label:         "Lanes",
    sc_team_eyebrow:        "Team setup",
    sc_add_team:            "+ Add team",
    sc_continue_scoring:    "Continue to scoring",
    sc_add_team_hint:       'Click "+ Add team" to start building teams.',
    sc_team_complete:       "Complete",
    sc_lane_eyebrow:        "Lane assignment",
    sc_lane_cont:           "Continue",
    sc_lane_prefix:         "Lane",
    sc_select_lane_hint:    "Select a lane above to start placing players.",
    sc_reg_eyebrow:         "Player registration",
    sc_select_all:          "Select all",
    sc_all_clubs:           "All clubs",
    sc_col_join:            "Join",
    sc_col_name:            "Name",
    sc_col_club:            "Club",
    sc_col_class:           "Class",
    sc_col_category:        "Category",
    sc_no_team:             "No team",
    sc_start_registered:    "Start with registered players",
    sc_eyebrow_scoring:     "Scoring",
    sc_contest_center:      "Contest center",
    sc_class_label:         "Class",
    sc_all_classes:         "All classes",
    sc_lane_label:          "Lane",
    sc_all_lanes:           "All lanes",
    sc_print_list:          "Print start list",
    sc_reset:               "Reset",
    sc_save_scores:         "Save scores",
    sc_col_player:          "Player",
    sc_col_rank:            "Rank",
    sc_col_points:          "Points",
    sc_col_1_5:             "1-5",
    sc_col_6_10:            "6-10",
    sc_col_total:           "Total",
    sc_col_7m:              "7m",
    sc_summary_title:       "Competition summary",
    sc_summary_desc:        "Editing values recalculates totals immediately. Saving stores this contest's scores in this browser so you can return to them from Old contest.",
    sc_class_prefix:        "Class",
    sc_player_s:            "player",
    sc_player_p:            "players",
    sc_team_s:              "team",
    sc_team_p:              "teams",
    sc_selected_suffix:     "selected",

    // ── Admin competitions page ────────────────────────────────────
    comps_admin_eyebrow:    "Competitions",
    comps_admin_heading:    "Competition list",
    comps_admin_desc:       "Synced from svhkf.se — add manual entries below.",
    comps_sync_loading:     "Syncing…",
    comps_sync_done:        "Synced!",
    comps_sync_error:       "Sync failed",
    comps_sync_btn:         "Sync from svhkf.se",
    comps_add_btn:          "Add competition",
    comps_new_heading:      "New competition",
    comps_form_name:        "Name",
    comps_form_name_ph:     "Competition name",
    comps_form_date:        "Date",
    comps_form_org:         "Organizer",
    comps_form_org_ph:      "Club name",
    comps_form_loc:         "Location",
    comps_form_loc_ph:      "Venue",
    comps_form_cancel:      "Cancel",
    comps_form_save:        "Save",
    comps_none:             'No competitions yet. Click "Sync from svhkf.se" or add one manually.',
    comps_col_name:         "Name",
    comps_col_date:         "Date",
    comps_col_org:          "Organizer",
    comps_col_loc:          "Location",
    comps_col_ranking:      "Ranking",
    comps_col_reg:          "Registration",
    comps_yes:              "Yes",
    comps_no:               "No",
    comps_delete:           "Delete",

    // ── Club page ──────────────────────────────────────────────────
    club_eyebrow:           "Club login",
    club_login_heading:     "Login as Club",
    club_login_desc:        "Enter your club name and password to continue.",
    club_login_user:        "Club name",
    club_login_user_ph:     "Select your club…",
    club_login_pass:        "Password",
    club_login_error:       "Wrong password. Contact the organizer.",
    club_login_btn:         "Login",
    club_logout:            "Logout",
    club_heading:           "Welcome",
    club_desc:              "Manage your club's players and register them for competitions.",
    club_tab_players:       "Club players",
    club_tab_competition:   "Competition registration",
    club_player_count:      "players in the club",
    club_add_player:        "Add player",
    club_name_ph:           "First and last name",
    club_no_players:        "No players added yet. Click \"Add player\" to get started.",
    club_no_comp:           "No competitions with open registration.",
    club_choose_comp:       "Choose competition",
    club_comp_placeholder:  "Select a competition…",
    club_choose_players:    "Choose players to register",
    club_selected:          "selected",
    club_submit_reg:        "Submit registration",
    club_reg_sent:          "Registration submitted! The organizer will confirm.",
    club_col_name:          "Name",
    club_col_club:          "Club",
    club_col_class:         "Class",
    club_col_category:      "Category",
    club_col_date:          "Registered",
    club_empty:             "No players registered yet.",
    club_back:              "Home",
    club_tab_own:               "Start own competition",
    club_own_pick_comp:         "Select your competition",
    club_own_registered_players:"Registered players",
    club_own_player_count:      "players",
    club_own_no_regs:           "No registrations yet for this competition.",
    club_own_none:              "Your club is not listed as organizer for any competition.",
    club_own_setup_type:        "Choose contest type",
    club_own_start:             "Start scoring",
    club_own_scoring:           "Live scoring",
    club_own_saved:             "Scores saved in this browser.",
    club_tab_incoming:      "Incoming registrations",
    club_incoming_eyebrow:  "Incoming registrations",
    club_incoming_desc:     "Players registered by other clubs for your competitions.",
    club_incoming_none_comp:"Your club is not listed as organizer for any competition.",
    club_incoming_empty:    "No registrations yet.",
    club_incoming_count:    "registered",
    club_incoming_time:     "Registered",
} as const;

const sv: typeof en = {
    // ── Header / brand ─────────────────────────────────────────────
    brand_subtitle:         "Tävlingsportal",

    // ── Public nav ─────────────────────────────────────────────────
    nav_registration:       "Registrera spelare",
    nav_login:              "Logga in",
    nav_login_admin:        "Logga in som Admin",
    nav_login_club:         "Logga in som Klubb",

    // ── Home hero ──────────────────────────────────────────────────
    hero_eyebrow:           "HSC Tävlingssystem",
    hero_title:             "Tävlingsportalen för hästskokastning.",
    hero_copy:              "Logga in som Admin för att hantera tävlingar och resultat, eller logga in som Klubb för att registrera era spelare.",
    hero_btn_login_admin:   "Logga in som Admin",
    hero_btn_login_club:    "Logga in som Klubb",

    // ── Home calendar panel ────────────────────────────────────────
    panel_kicker:           "Säsong 2026",
    panel_heading:          "Kommande tävlingar",
    panel_empty:            "Inga kommande tävlingar hittades.",
    panel_view_all:         "Visa alla tävlingar",
    status_open:            "Öppen",
    status_closed:          "Stängd",

    // ── Competitions public page ───────────────────────────────────
    back_home:              "Hem",
    comps_eyebrow:          "Säsong 2026",
    comps_heading:          "Alla tävlingar",
    comps_copy:             "Hela säsongens kalender synkad från svhkf.se.",
    comps_upcoming:         "Kommande",
    comps_past:             "Avslutade",
    comps_empty:            "Inga tävlingar hittades. Kolla igen senare.",
    ranking:                "Ranking",

    // ── Registration page ──────────────────────────────────────────
    reg_back_home:          "Hem",
    reg_back_public:        "Startsida",
    reg_eyebrow:            "Registrera spelare",
    reg_heading:            "Registrera en spelare till nästa HSC-tävling.",
    reg_copy:               "Fyll i spelaruppgifter så att arrangörerna kan bekräfta kategorier, klubbar och poängblad innan tävlingen börjar.",
    reg_point_1:            "Bekräftelse hanteras av arrangören",
    reg_point_2:            "Stöder singel- och laganmälningar",
    reg_point_3:            "Kontaktuppgifter sparas i tävlingslistan",
    reg_kicker:             "Spelarregistrering",
    reg_form_heading:       "Spelaruppgifter",
    reg_received:           "Mottagen",
    reg_first_name:         "Förnamn",
    reg_last_name:          "Efternamn",
    reg_email:              "E-post",
    reg_optional:           "(valfritt)",
    reg_club:               "Klubb",
    reg_search:             "Skriv för att söka...",
    reg_class:              "Klass",
    reg_select_class:       "Välj klass",
    reg_class_1:            "Klass 1",
    reg_class_2:            "Klass 2",
    reg_class_3:            "Klass 3",
    reg_class_4:            "Klass 4",
    reg_title:              "Titel",
    reg_select_title:       "Välj titel",
    reg_mr:                 "Herr",
    reg_mrs:                "Fru",
    reg_junior:             "Junior",
    reg_minior:             "Minior",
    reg_notes:              "Anteckningar",
    reg_notes_ph:           "Partner, tillgänglighetsbehov eller schemaanteckningar",
    reg_submit:             "Skicka anmälan",
    reg_saved:              "Anmälan sparad i webbläsaren. Du kan koppla den till Supabase när tävlings-API:et är klart.",

    // ── Admin sidebar ──────────────────────────────────────────────
    sidebar_subtitle:       "Tävlingssystem",
    menu_dashboard:         "Instrumentpanel",
    menu_players:           "Spelare",
    menu_competitions:      "Tävlingar",
    menu_registration:      "Registrera spelare",
    menu_contest:           "Tävling",
    menu_results:           "Resultat",
    menu_reports:           "Rapporter",
    menu_settings:          "Inställningar",

    // ── Topbar ─────────────────────────────────────────────────────
    topbar_title:           "Tävlingsadmin",
    topbar_role:            "Tävlingsledare",
    topbar_notifications:   "Aviseringar",

    // ── Dashboard ──────────────────────────────────────────────────
    dash_eyebrow:           "Inloggad",
    dash_heading:           "Vad vill du göra?",
    dash_card_reg_title:    "Registrera spelare",
    dash_card_reg_text:     "Lägg till en ny spelare med klubb, kategori och tävlingsuppgifter.",
    dash_card_teams_title:  "Lag och spelare",
    dash_card_teams_text:   "Se hela startlistan och granska alla klubbar, lag, klasser och kategorier.",
    dash_card_start_title:  "Starta tävling",
    dash_card_start_text:   "Öppna poängsättning för den aktiva tävlingen och börja mata in resultat.",
    dash_current_comp:      "Aktuell tävling",

    // ── Players page ───────────────────────────────────────────────
    players_eyebrow:        "Startlista",
    players_clubs_heading:  "Klubbar",
    players_club_desc:      "Välj en klubb för att se dess medlemmar.",
    players_team_desc:      "Klubbmedlemmar sorterade efter klass och namn.",
    players_all_clubs:      "Alla klubbar",
    players_col_class:      "Klass",
    players_col_name:       "Namn",
    players_col_category:   "Kategori",
    players_col_7m:         "7-meter",
    players_col_actions:    "Åtgärder",
    players_edit_btn:       "Redigera",
    players_no_team:        "Inget lag",
    players_class_prefix:   "Klass",
    players_player_s:       "spelare",
    players_player_p:       "spelare",
    players_member_s:       "medlem",
    players_member_p:       "medlemmar",
    players_classes_sfx:    "klasser",
    players_label_name:     "Namn",
    players_label_club:     "Klubb",
    players_label_class:    "Klass",
    players_label_category: "Kategori",
    players_save:           "Spara",
    players_cancel:         "Avbryt",

    // ── Results page ───────────────────────────────────────────────
    results_empty_heading:  "Ingen aktiv tävling",
    results_empty_desc:     "Starta en tävling i Tävlingscenter för att se liveresultat här.",
    results_eyebrow:        "Liveresultat",
    results_updates_auto:   "uppdateras automatiskt",
    results_print:          "Skriv ut",
    results_class_prefix:   "Klass",
    results_col_player:     "Spelare",
    results_col_club:       "Klubb",
    results_col_total:      "Totalt",
    results_col_7m:         "7m",
    results_col_points:     "Poäng",
    results_col_num:        "#",
    results_player_s:       "spelare",
    results_player_p:       "spelare",
    results_team_heading:   "Lag",
    results_team_s:         "lag",
    results_team_p:         "lag",
    results_col_teams_name: "Lag",
    results_col_players:    "Spelare",

    // ── Contest / Scoring page ─────────────────────────────────────
    sc_eyebrow_menu:        "Tävling",
    sc_heading_menu:        "Tävlingscenter",
    sc_desc_menu:           "Starta en ny tävling eller öppna en sparad tävling.",
    sc_start_title:         "Starta tävling",
    sc_start_desc:          "Välj vilken tävling du vill starta.",
    sc_old_title:           "Gammal tävling",
    sc_old_desc:            "Öppna en tävling med poäng sparade i denna webbläsare.",
    sc_back:                "Tillbaka",
    sc_heading_choose:      "Välj tävling",
    sc_desc_choose:         "Välj vilken tävling du vill starta.",
    sc_heading_saved:       "Sparade tävlingar",
    sc_desc_saved:          "Välj en sparad tävling för att fortsätta poängsättningen.",
    sc_no_old_heading:      "Inga gamla tävlingar",
    sc_no_old_pill:         "Tom",
    sc_no_old_desc:         "Sparade tävlingar visas här efter att du startat en tävling och sparat poäng.",
    sc_type_desc:           "Välj en eller flera tävlingstyper. Klicka på en vald typ igen för att avmarkera.",
    sc_clear:               "Rensa",
    sc_continue:            "Fortsätt",
    sc_lanes_label:         "Banor",
    sc_team_eyebrow:        "Laguppställning",
    sc_add_team:            "+ Lägg till lag",
    sc_continue_scoring:    "Fortsätt till poängsättning",
    sc_add_team_hint:       'Klicka på "+ Lägg till lag" för att börja bygga lag.',
    sc_team_complete:       "Komplett",
    sc_lane_eyebrow:        "Bantilldelning",
    sc_lane_cont:           "Fortsätt",
    sc_lane_prefix:         "Bana",
    sc_select_lane_hint:    "Välj en bana ovan för att börja placera spelare.",
    sc_reg_eyebrow:         "Spelaranmälan",
    sc_select_all:          "Välj alla",
    sc_all_clubs:           "Alla klubbar",
    sc_col_join:            "Anslut",
    sc_col_name:            "Namn",
    sc_col_club:            "Klubb",
    sc_col_class:           "Klass",
    sc_col_category:        "Kategori",
    sc_no_team:             "Inget lag",
    sc_start_registered:    "Starta med registrerade spelare",
    sc_eyebrow_scoring:     "Poängsättning",
    sc_contest_center:      "Tävlingscenter",
    sc_class_label:         "Klass",
    sc_all_classes:         "Alla klasser",
    sc_lane_label:          "Bana",
    sc_all_lanes:           "Alla banor",
    sc_print_list:          "Skriv ut startlista",
    sc_reset:               "Återställ",
    sc_save_scores:         "Spara poäng",
    sc_col_player:          "Spelare",
    sc_col_rank:            "Plats",
    sc_col_points:          "Poäng",
    sc_col_1_5:             "1-5",
    sc_col_6_10:            "6-10",
    sc_col_total:           "Totalt",
    sc_col_7m:              "7m",
    sc_summary_title:       "Tävlingsöversikt",
    sc_summary_desc:        "Att redigera värden räknar om summor direkt. Att spara lagrar denna tävlings poäng i webbläsaren så du kan återvända från Gammal tävling.",
    sc_class_prefix:        "Klass",
    sc_player_s:            "spelare",
    sc_player_p:            "spelare",
    sc_team_s:              "lag",
    sc_team_p:              "lag",
    sc_selected_suffix:     "valda",

    // ── Admin competitions page ────────────────────────────────────
    comps_admin_eyebrow:    "Tävlingar",
    comps_admin_heading:    "Tävlingslista",
    comps_admin_desc:       "Synkad från svhkf.se — lägg till manuella poster nedan.",
    comps_sync_loading:     "Synkar…",
    comps_sync_done:        "Synkad!",
    comps_sync_error:       "Synkning misslyckades",
    comps_sync_btn:         "Synka från svhkf.se",
    comps_add_btn:          "Lägg till tävling",
    comps_new_heading:      "Ny tävling",
    comps_form_name:        "Namn",
    comps_form_name_ph:     "Tävlingsnamn",
    comps_form_date:        "Datum",
    comps_form_org:         "Arrangör",
    comps_form_org_ph:      "Klubbnamn",
    comps_form_loc:         "Plats",
    comps_form_loc_ph:      "Plats",
    comps_form_cancel:      "Avbryt",
    comps_form_save:        "Spara",
    comps_none:             'Inga tävlingar än. Klicka på "Synka från svhkf.se" eller lägg till en manuellt.',
    comps_col_name:         "Namn",
    comps_col_date:         "Datum",
    comps_col_org:          "Arrangör",
    comps_col_loc:          "Plats",
    comps_col_ranking:      "Ranking",
    comps_col_reg:          "Anmälan",
    comps_yes:              "Ja",
    comps_no:               "Nej",
    comps_delete:           "Ta bort",

    // ── Club page ──────────────────────────────────────────────────
    club_eyebrow:           "Klubbinloggning",
    club_login_heading:     "Logga in som Klubb",
    club_login_desc:        "Ange ert klubbnamn och lösenord för att fortsätta.",
    club_login_user:        "Klubbnamn",
    club_login_user_ph:     "Välj din klubb…",
    club_login_pass:        "Lösenord",
    club_login_error:       "Fel lösenord. Kontakta arrangören.",
    club_login_btn:         "Logga in",
    club_logout:            "Logga ut",
    club_heading:           "Välkommen",
    club_desc:              "Hantera klubbens spelare och anmäl dem till tävlingar.",
    club_tab_players:       "Spelare i klubben",
    club_tab_competition:   "Tävlingsanmälan",
    club_player_count:      "spelare i klubben",
    club_add_player:        "Lägg till spelare",
    club_name_ph:           "För- och efternamn",
    club_no_players:        "Inga spelare tillagda. Klicka på \"Lägg till spelare\" för att börja.",
    club_no_comp:           "Inga tävlingar med öppen anmälan.",
    club_choose_comp:       "Välj tävling",
    club_comp_placeholder:  "Välj en tävling…",
    club_choose_players:    "Välj spelare att anmäla",
    club_selected:          "valda",
    club_submit_reg:        "Skicka anmälan",
    club_reg_sent:          "Anmälan skickad! Arrangören bekräftar.",
    club_col_name:          "Namn",
    club_col_club:          "Klubb",
    club_col_class:         "Klass",
    club_col_category:      "Kategori",
    club_col_date:          "Registrerad",
    club_empty:             "Inga spelare registrerade ännu.",
    club_back:              "Hem",
    club_tab_own:               "Starta egen tävling",
    club_own_pick_comp:         "Välj din tävling",
    club_own_registered_players:"Anmälda spelare",
    club_own_player_count:      "spelare",
    club_own_no_regs:           "Inga anmälningar ännu till denna tävling.",
    club_own_none:              "Din klubb är inte listad som arrangör för någon tävling.",
    club_own_setup_type:        "Välj tävlingstyp",
    club_own_start:             "Starta poängsättning",
    club_own_scoring:           "Live-poängsättning",
    club_own_saved:             "Poäng sparade i webbläsaren.",
    club_tab_incoming:      "Inkommande anmälningar",
    club_incoming_eyebrow:  "Inkommande anmälningar",
    club_incoming_desc:     "Spelare anmälda av andra klubbar till era tävlingar.",
    club_incoming_none_comp:"Din klubb är inte listad som arrangör för någon tävling.",
    club_incoming_empty:    "Inga anmälningar ännu.",
    club_incoming_count:    "anmälda",
    club_incoming_time:     "Anmäldes",
};

const translations = { en, sv } as const;
type Translations = typeof en;

interface LangContextValue {
    lang: Lang;
    setLang: (l: Lang) => void;
    t: Translations;
}

const LangContext = createContext<LangContextValue>({
    lang: "sv",
    setLang: () => {},
    t: sv,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<Lang>(() => {
        const stored = localStorage.getItem("hsc-lang");
        return stored === "en" || stored === "sv" ? stored : "sv";
    });

    function setLang(l: Lang) {
        localStorage.setItem("hsc-lang", l);
        setLangState(l);
    }

    return (
        <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
            {children}
        </LangContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LangContext);
}
